version: '3'
services:
  db:
    image: postgres:12.1-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
  app:
    build: .
    command: sh launch.sh
    volumes:
      - .:/myapp
      - public_volume:/myapp/public
      - tmp_volume:/myapp/tmp
      - log_volume:/myapp/log
      - ./vendor/bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - public_volume:/myapp/public
      - tmp_volume:/myapp/tmp
    ports:
      - 80:80
    restart: always
    network_mode: host
    depends_on:
      - app
volumes:
  public_volume:
  tmp_volume:
  log_volume:
  pg_data:
    driver: local